version: '3.9'

services:
  redis:
    image: redis:alpine

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=futurecloud
      - POSTGRES_DB=futurecloud
      - POSTGRES_PASSWORD=Secret
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U futurecloud" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: development.Dockerfile
    ports:
      - 8899:80
    env_file: development.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
    - "./app:/app/app"