name: Build Docker

on:
  push:
    branches:
      - 'develop'
    tags:
      - "v*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Get Latest Tag
        uses: oprypin/find-latest-tag@v1
        id: raw_latest_tag
      -
        name: Trim Latest Tag
        id: latest_tag
        run: tag="${{ steps.raw_latest_tag.outputs.tag }}" && echo ${tag:1:20}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
          push: true
          tags: tert0/futurecloud-backend:latest, tert0/futurecloud-backend:${{ steps.latest_tag.outputs }}